site_name: Aplicação de Redes de Computadores
site_author: Ana Clara Bezerra Bonifacio
theme:
  name: material
  language: pt

repo_name: 
repo_url: https://anaclrra.github.io/apr-2023.2/

nav:
- index.md
- pedra.md
- papel.md
- tesoura.md
- Ensaios:
  - ensaios/mermaid.md

plugins:
  - mermaid2